name: Final QA Automation Project WorkFlow

on:
  push:
    branches:
      - main
jobs: 
  Running-Jobs-For-Project:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10'
      - run: python --version
      - run: pip install -r requirements.txt
      
